FROM php:7.4-apache

COPY Docker/000-default.conf /etc/apache2/sites-enabled/000-default.conf

# Install dependencies and Composer
RUN apt-get update \
    && apt-get install -y git zip unzip libzip-dev \
    && apt update \
    && apt install nano \
    && php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN apt-get install -y libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-install zip

RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev && \
    docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ && \
    docker-php-ext-install gd

RUN docker-php-ext-install pdo

RUN docker-php-ext-install pdo_mysql


# Enable mod_rewrite
RUN a2enmod rewrite

# Copy custom PHP configuration file
COPY Docker/custom.ini /usr/local/etc/php/conf.d/

# Add user and group for application
ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password -u $USER_ID --ingroup user user

# Change the current user to user
USER user
# Set working directory
WORKDIR /var/www/html

# Expose port 80 for web access
EXPOSE 80