version: '3'

services:
  mysql8_vida7:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql8_vida7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: vida
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3377:3306"
    volumes:
      - ./Docker/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./database:/var/lib/mysql
    depends_on:
      - php8_vida7

  php8_vida7:
    container_name: php8_vida7
    build:
      context: .
      dockerfile: Docker/Dockerfile-php
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: always
    ports:
      - "8091:80"
    volumes:
      - ./:/var/www/html/
    environment:
      DB_SERVER: mysql8_vida7
      DB_NAME: vida
      DB_USER: user
      DB_PASSWD: password

volumes:
  database: